# Generated by Django 6.0.6 on 2026-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0001_initial'),
        ('master', '0006_task_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='進捗（%）'),
        ),
        migrations.AlterUniqueTogether(
            name='actual',
            unique_together={('member', 'task', 'date')},
        ),
    ]
