# Generated by Django 6.0.6 on 2026-07-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0002_actual_progress_alter_actual_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual',
            name='progress',
        ),
    ]
