# Generated by Django 6.0.6 on 2026-07-01 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='メンバー名')),
            ],
            options={
                'verbose_name': 'メンバー',
                'verbose_name_plural': 'メンバー',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='作業名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '作業',
                'verbose_name_plural': '作業',
            },
        ),
    ]
