# Generated by Django 6.0.6 on 2026-07-01 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_task_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='進捗率(%)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.task', verbose_name='作業')),
            ],
            options={
                'verbose_name': '進捗率',
                'verbose_name_plural': '進捗率',
                'unique_together': {('task', 'date')},
            },
        ),
    ]
