# Generated by Django 6.0.6 on 2026-07-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_task_progress_taskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#4a90d9', max_length=7, verbose_name='表示色'),
        ),
    ]
