# Generated by Django 5.1 on 2026-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='予定工数（時間）'),
        ),
    ]
