# Generated by Django 6.0.6 on 2026-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_task_planned_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.CharField(choices=[('design', '設計'), ('develop', '製造'), ('review', 'レビュー'), ('test', 'テスト'), ('other', 'その他')], default='other', max_length=20, verbose_name='フェーズ'),
        ),
    ]
