# Generated by Django 6.0.6 on 2026-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_task_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='進捗（%）'),
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
