# Generated by Django 6.0.6 on 2026-07-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_task_progress_delete_taskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='単価（円/時）'),
        ),
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='金額（円）'),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='納品日'),
        ),
    ]
