# Generated by Django 6.0.6 on 2026-07-01 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='予定時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.member', verbose_name='メンバー')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.task', verbose_name='作業')),
            ],
            options={
                'verbose_name': '予定',
                'verbose_name_plural': '予定',
            },
        ),
    ]
