# Generated by Django 6.0.6 on 2026-07-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='start_slot',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='開始コマ目'),
        ),
    ]
